/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  SetUpCapSkuAllLegacyRequest,
  setUpCapSkuAllLegacyRequestSchema,
} from '../models/setUpCapSkuAllLegacyRequest.js';
import {
  SuccessfulOperation12,
  successfulOperation12Schema,
} from '../models/successfulOperation12.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class CppreferenceApi extends BaseApi {
  /**
   * This API helps Sellers to completely opt-in or opt-out from CAP program.
   *
   * If the subsidyEnrolled value = "true", the Seller enrolls in the CAP program. All eligible SKUs
   * (current and future) are by default opt-in. Seller should use the SKU opt-in/opt-out API to opt-out
   * individual items.
   *
   * If the subsidyEnrolled value = "false", the Seller stops participating in the CAP program and all
   * eligible SKUs (current and future) are opt-out of the CAP program.
   *
   * @param wmSecAccessToken         The access token retrieved in the Token API
   *                                                                       call
   * @param wmConsumerChannelType    A unique ID to track the consumer request
   *                                                                       by channel. Use the Consumer Channel Type
   *                                                                       received during onboarding
   * @param wmQosCorrelationId       A unique ID which identifies each API call
   *                                                                       and used to track and debug issues; use a
   *                                                                       random generated GUID for this ID
   * @param wmSvcName                Walmart Service Name
   * @param accept
   * @param body
   * @return Response from the API call
   */
  async setUpCapSkuAllLegacy(
    wmSecAccessToken: string,
    wmConsumerChannelType: string,
    wmQosCorrelationId: string,
    wmSvcName: string,
    accept: string,
    body: SetUpCapSkuAllLegacyRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SuccessfulOperation12>> {
    const req = this.createRequest('POST', '/cppreference');
    const mapped = req.prepareArgs({
      wmSecAccessToken: [wmSecAccessToken, string()],
      wmConsumerChannelType: [wmConsumerChannelType, string()],
      wmQosCorrelationId: [wmQosCorrelationId, string()],
      wmSvcName: [wmSvcName, string()],
      accept: [accept, string()],
      body: [body, setUpCapSkuAllLegacyRequestSchema],
    });
    req.header('WM_SEC.ACCESS_TOKEN', mapped.wmSecAccessToken);
    req.header('WM_CONSUMER.CHANNEL.TYPE', mapped.wmConsumerChannelType);
    req.header('WM_QOS.CORRELATION_ID', mapped.wmQosCorrelationId);
    req.header('WM_SVC.NAME', mapped.wmSvcName);
    req.header('Content-Type', 'application/json');
    req.header('Accept', mapped.accept);
    req.json(mapped.body);
    req.authenticate(false);
    return req.callAsJson(successfulOperation12Schema, requestOptions);
  }
}
