/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  SuccessfulOperation2,
  successfulOperation2Schema,
} from '../models/successfulOperation2.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class DetailApi extends BaseApi {
  /**
   * Returns OAuth token metadata and scopes granted by the seller to your application. Use this to
   * verify whether a token is valid, when it expires, and which API categories are allowed (full_access,
   * view_only, no_access). Send the access token in the `WM_SEC.ACCESS_TOKEN` header.
   *
   * You can also use this API for troubleshooting access failures and rendering “connected account”
   * permissions in your UI. For more information and usage examples, refer to <a href="https://developer.
   * walmart.com/us-marketplace/docs/retrieve-access-token-details">Retrieve access token details.</a>
   *
   * @param wmSecAccessToken         Access token obtained from the Token API. This is required for
   *                                           authenticating requests to Walmart Marketplace APIs.
   * @param wmConsumerChannelType    A unique ID to track the consumer request by channel. Use the Consumer
   *                                           Channel Type received during onboarding.
   * @param wmQosCorrelationId       A unique ID that identifies each API call and is used to track and
   *                                           debug issues. Use a randomly generated GUID for this ID.
   * @param wmSvcName                Specifies the name of the Walmart service being called.
   * @param accept
   * @return Response from the API call
   */
  async tokenDetail(
    wmSecAccessToken: string,
    wmConsumerChannelType: string,
    wmQosCorrelationId: string,
    wmSvcName: string,
    accept: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SuccessfulOperation2>> {
    const req = this.createRequest('GET', '/token/detail');
    const mapped = req.prepareArgs({
      wmSecAccessToken: [wmSecAccessToken, string()],
      wmConsumerChannelType: [wmConsumerChannelType, string()],
      wmQosCorrelationId: [wmQosCorrelationId, string()],
      wmSvcName: [wmSvcName, string()],
      accept: [accept, string()],
    });
    req.header('WM_SEC.ACCESS_TOKEN', mapped.wmSecAccessToken);
    req.header('WM_CONSUMER.CHANNEL.TYPE', mapped.wmConsumerChannelType);
    req.header('WM_QOS.CORRELATION_ID', mapped.wmQosCorrelationId);
    req.header('WM_SVC.NAME', mapped.wmSvcName);
    req.header('Accept', mapped.accept);
    req.authenticate([{ basic: true }]);
    return req.callAsJson(successfulOperation2Schema, requestOptions);
  }
}
