/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  SuccessfulOperation11,
  successfulOperation11Schema,
} from '../models/successfulOperation11.js';
import {
  UpdateReducedReferralFeeIncentivesEnrollmentRequest,
  updateReducedReferralFeeIncentivesEnrollmentRequestSchema,
} from '../models/updateReducedReferralFeeIncentivesEnrollmentRequest.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class FeedsFeedTypeIncentiveEnrollmentApi extends BaseApi {
  /**
   * You can use this API endpoint to enroll any eligible item to Reduced Referral Fee incentive. You can
   * also use this endpoint to unenroll any items from active Reduced Referral Fee incentives.
   *
   * For more information and usage examples, refer to the <a href="https://developer.walmart.com/us-
   * marketplace/docs/enroll-in-reduced-referral-fee-incentives">Pricing API Guide</a>.
   *
   * @param feedType
   * @param wmSecAccessToken         Access token
   *                                                                                               obtained from the
   *                                                                                               Token API. This is
   *                                                                                               required for
   *                                                                                               authenticating
   *                                                                                               requests to Walmart
   *                                                                                               Marketplace APIs.
   * @param wmConsumerChannelType    A unique ID to
   *                                                                                               track the consumer
   *                                                                                               request by channel.
   *                                                                                               Use the Consumer
   *                                                                                               Channel Type
   *                                                                                               received during
   *                                                                                               onboarding.
   * @param wmQosCorrelationId       A unique ID that
   *                                                                                               identifies each API
   *                                                                                               call and is used to
   *                                                                                               track and debug
   *                                                                                               issues. Use a
   *                                                                                               randomly generated
   *                                                                                               GUID for this ID.
   * @param wmSvcName                Specifies the name
   *                                                                                               of the Walmart
   *                                                                                               service being called.
   * @param accept
   * @param body
   * @return Response from the API call
   */
  async updateReducedReferralFeeIncentivesEnrollment(
    feedType: string,
    wmSecAccessToken: string,
    wmConsumerChannelType: string,
    wmQosCorrelationId: string,
    wmSvcName: string,
    accept: string,
    body: UpdateReducedReferralFeeIncentivesEnrollmentRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SuccessfulOperation11>> {
    const req = this.createRequest('POST', '/feeds');
    const mapped = req.prepareArgs({
      feedType: [feedType, string()],
      wmSecAccessToken: [wmSecAccessToken, string()],
      wmConsumerChannelType: [wmConsumerChannelType, string()],
      wmQosCorrelationId: [wmQosCorrelationId, string()],
      wmSvcName: [wmSvcName, string()],
      accept: [accept, string()],
      body: [body, updateReducedReferralFeeIncentivesEnrollmentRequestSchema],
    });
    req.header('WM_SEC.ACCESS_TOKEN', mapped.wmSecAccessToken);
    req.header('WM_CONSUMER.CHANNEL.TYPE', mapped.wmConsumerChannelType);
    req.header('WM_QOS.CORRELATION_ID', mapped.wmQosCorrelationId);
    req.header('WM_SVC.NAME', mapped.wmSvcName);
    req.header('Content-Type', 'application/json');
    req.header('Accept', mapped.accept);
    req.query('feedType', mapped.feedType);
    req.json(mapped.body);
    req.authenticate(false);
    return req.callAsJson(successfulOperation11Schema, requestOptions);
  }
}
