/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  SuccessfulOperation8,
  successfulOperation8Schema,
} from '../models/successfulOperation8.js';
import {
  UpdatePricingForMultipleItemsInBulkNewRequest,
  updatePricingForMultipleItemsInBulkNewRequestSchema,
} from '../models/updatePricingForMultipleItemsInBulkNewRequest.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class FeedsFeedTypePriceAndPromotionApi extends BaseApi {
  /**
   * Updates the price and promotions in bulk for multiple items. You can modify the prices of multiple
   * items in bulk using a price feed. This is useful for implementing pricing strategies across your
   * catalog, such as seasonal discounts, competitive pricing adjustments, or clearance sales.
   *
   * Each price feed can contain up to 10,000 items. To ensure optimal performance (feed processing time),
   * we recommend limiting the feeds to 1,000 items and keeping the payload under 10 MB.
   *
   * The price sequence guarantee is observed by the bulk price update functionality, subject to the
   * following rules:
   *
   * Use this API instead of the single price update API, especially if a new item has been set up and a
   * Walmart Part ID (wpid) is available. Ensure to wait at least 24 hours after item creation to use the
   * bulk price update API. The bulk price update Service Level Agreement (SLA) is 15 minutes.
   *
   * You may include the same Stock Keeping Unit (SKU) multiple times in a single feed. However, if a SKU
   * is repeated in a feed, only on price will be applied. The price sequence guarantee ensures that the
   * latest price update, based on its creation timestamp, is the one that changes the price of the item,
   * overwriting the previous version. Price updates received with an earlier timestamp are ignored. As a
   * result, we recommend all feed-based bulk updates base the value of `feedDate` on UTC.
   *
   * After submitting the price feed, wait at least 5 minutes before checking whether the bulk price
   * update was successful. If a price update fails, for example due to duplicate SKU entries, an error
   * response will be returned.
   *
   * For more information and usage examples, refer to the <a href="https://developer.walmart.com/us-
   * marketplace/reference/priceandpromotionbulkuploads">Pricing API Guide</a>.
   *
   * @param feedType
   * @param wmSecAccessToken         Access token obtained
   *                                                                                         from the Token API. This
   *                                                                                         is required for
   *                                                                                         authenticating requests to
   *                                                                                         Walmart Marketplace APIs.
   * @param wmConsumerChannelType    A unique ID to track the
   *                                                                                         consumer request by
   *                                                                                         channel. Use the Consumer
   *                                                                                         Channel Type received
   *                                                                                         during onboarding.
   * @param wmQosCorrelationId       A unique ID that
   *                                                                                         identifies each API call
   *                                                                                         and is used to track and
   *                                                                                         debug issues. Use a
   *                                                                                         randomly generated GUID
   *                                                                                         for this ID.
   * @param wmSvcName                Specifies the name of the
   *                                                                                         Walmart service being
   *                                                                                         called.
   * @param accept
   * @param body
   * @return Response from the API call
   */
  async updatePricingForMultipleItemsInBulkNew(
    feedType: string,
    wmSecAccessToken: string,
    wmConsumerChannelType: string,
    wmQosCorrelationId: string,
    wmSvcName: string,
    accept: string,
    body: UpdatePricingForMultipleItemsInBulkNewRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SuccessfulOperation8>> {
    const req = this.createRequest('POST', '/feeds');
    const mapped = req.prepareArgs({
      feedType: [feedType, string()],
      wmSecAccessToken: [wmSecAccessToken, string()],
      wmConsumerChannelType: [wmConsumerChannelType, string()],
      wmQosCorrelationId: [wmQosCorrelationId, string()],
      wmSvcName: [wmSvcName, string()],
      accept: [accept, string()],
      body: [body, updatePricingForMultipleItemsInBulkNewRequestSchema],
    });
    req.header('WM_SEC.ACCESS_TOKEN', mapped.wmSecAccessToken);
    req.header('WM_CONSUMER.CHANNEL.TYPE', mapped.wmConsumerChannelType);
    req.header('WM_QOS.CORRELATION_ID', mapped.wmQosCorrelationId);
    req.header('WM_SVC.NAME', mapped.wmSvcName);
    req.header('Content-Type', 'application/json');
    req.header('Accept', mapped.accept);
    req.query('feedType', mapped.feedType);
    req.json(mapped.body);
    req.authenticate(false);
    return req.callAsJson(successfulOperation8Schema, requestOptions);
  }
}
