/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, FileWrapper, RequestOptions } from '../core.js';
import { Json1, json1Schema } from '../models/json1.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class FeedsApi extends BaseApi {
  /**
   * Updates prices in bulk.
   *
   * In one Feed you can update up to 10,000 items in bulk. To ensure optimal Feed processing time, we
   * recommend sending no more than 1000 items in one Feed and keeping the Feed sizes below 10 MB.
   *
   * The price sequence guarantee is observed by the bulk price update functionality, subject to the
   * following rules:
   *
   * The timestamp used to determine precedence is passed in the request headers. All price updates in
   * the feed are considered to have the same timestamp. The timestamp in the XML file is used only for
   * auditing.
   * You can send a single SKU multiple times in one Feed. If a SKU is repeated in a Feed, the price will
   * be set for that SKU on Walmart.com, but there is no guarantee as to which SKU's price within that
   * feed will be used.
   * This API should be used in preference to the update a price. It should be called no sooner than 24
   * hours after a new item is set up and a wpid (Walmart Part ID) is available. Thereafter, the bulk
   * price update has an service level agreement (SLA) of 15 minutes.
   *
   * After the update is submitted, wait for at least five minutes before verifying whether the bulk
   * price update was successful. Individual SKU price update success or failure is only available after
   * the entire feed is processed.
   *
   * If a SKU's price update fails (for example, multiple price updates were sent for the same SKU in a
   * single feed), an error will be returned.
   *
   * <b>You can download the request body sample from <a href="/file/mp/us/price-feed.zip">here</a></b>
   *
   * @param feedType                 The feed Type
   * @param wmSecAccessToken         The access token retrieved in the Token API call
   * @param wmConsumerChannelType    A unique ID to track the consumer request by channel. Use the
   *                                                Consumer Channel Type received during onboarding
   * @param wmQosCorrelationId       A unique ID which identifies each API call and used to track and
   *                                                debug issues; use a random generated GUID for this ID
   * @param wmSvcName                Walmart Service Name
   * @param accept
   * @param file                     Feed file to upload
   * @return Response from the API call
   */
  async updateBulkPricesLegacy(
    feedType: string,
    wmSecAccessToken: string,
    wmConsumerChannelType: string,
    wmQosCorrelationId: string,
    wmSvcName: string,
    accept: string,
    file: FileWrapper,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Json1>> {
    const req = this.createRequest('POST', '/feeds');
    const mapped = req.prepareArgs({
      feedType: [feedType, string()],
      wmSecAccessToken: [wmSecAccessToken, string()],
      wmConsumerChannelType: [wmConsumerChannelType, string()],
      wmQosCorrelationId: [wmQosCorrelationId, string()],
      wmSvcName: [wmSvcName, string()],
      accept: [accept, string()],
    });
    req.header('WM_SEC.ACCESS_TOKEN', mapped.wmSecAccessToken);
    req.header('WM_CONSUMER.CHANNEL.TYPE', mapped.wmConsumerChannelType);
    req.header('WM_QOS.CORRELATION_ID', mapped.wmQosCorrelationId);
    req.header('WM_SVC.NAME', mapped.wmSvcName);
    req.header('Content-Type', 'multipart/form-data');
    req.header('Accept', mapped.accept);
    req.query('feedType', mapped.feedType);
    req.formData({ file: file });
    req.authenticate(false);
    return req.callAsJson(json1Schema, requestOptions);
  }
}
