/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  SuccessfulOperation8,
  successfulOperation8Schema,
} from '../models/successfulOperation8.js';
import {
  UpdateWalmartFundedIncentivesEnrollmentForSpecificItemsRequest,
  updateWalmartFundedIncentivesEnrollmentForSpecificItemsRequestSchema,
} from '../models/updateWalmartFundedIncentivesEnrollmentForSpecificItemsRequest.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class FeedsFeedTypeWalmartFundedIncentivesEnrollmentApi extends BaseApi {
  /**
   * Updates the enrollment status of specific items in the Walmart-funded incentives program. By default,
   * all items are auto-enrolled in Walmart-funded incentives, meaning that eligible items are
   * automatically included in this program to benefit from price reductions funded by Walmart.
   *
   * You have the flexibility to modify the enrollment status for specific items using this API:
   * <ul><li>Opt-Out - Use this option to opt-out of Walmart-funded incentives for specific items for
   * which you do not want to lower the price.</li> <li>Opt-in - Use this option to opt-in items that
   * were previously opted-out from Walmart-funded incentives. For instance, you can re-enroll items in
   * Walmart-funded incentives programs at any time depending on your business needs.</li></ul>
   *
   * For more information and usage examples, refer to the <a href="https://developer.walmart.com/us-
   * marketplace/docs/manage-enrollment-specific-items-in-walmart-funded-incentives">Pricing API
   * Guide</a>.
   *
   * @param feedType
   * @param wmSecAccessToken         Access
   *                                                                                                          token
   *                                                                                                          obtained
   *                                                                                                          from the
   *                                                                                                          Token API.
   *                                                                                                          This is
   *                                                                                                          required
   *                                                                                                          for
   *                                                                                                          authentic
   *                                                                                                          ating
   *                                                                                                          requests
   *                                                                                                          to
   *                                                                                                          Walmart
   *                                                                                                          Marketpla
   *                                                                                                          ce APIs.
   * @param wmConsumerChannelType    A unique
   *                                                                                                          ID to
   *                                                                                                          track the
   *                                                                                                          consumer
   *                                                                                                          request
   *                                                                                                          by
   *                                                                                                          channel.
   *                                                                                                          Use the
   *                                                                                                          Consumer
   *                                                                                                          Channel
   *                                                                                                          Type
   *                                                                                                          received
   *                                                                                                          during
   *                                                                                                          onboardin
   *                                                                                                          g.
   * @param wmQosCorrelationId       A unique
   *                                                                                                          ID that
   *                                                                                                          identifie
   *                                                                                                          s each
   *                                                                                                          API call
   *                                                                                                          and is
   *                                                                                                          used to
   *                                                                                                          track and
   *                                                                                                          debug
   *                                                                                                          issues.
   *                                                                                                          Use a
   *                                                                                                          randomly
   *                                                                                                          generated
   *                                                                                                          GUID for
   *                                                                                                          this ID.
   * @param wmSvcName                
   *                                                                                                          Specifies
   *                                                                                                          the name
   *                                                                                                          of the
   *                                                                                                          Walmart
   *                                                                                                          service
   *                                                                                                          being
   *                                                                                                          called.
   * @param accept
   * @param body
   * @return Response from the API call
   */
  async updateWalmartFundedIncentivesEnrollmentForSpecificItems(
    feedType: string,
    wmSecAccessToken: string,
    wmConsumerChannelType: string,
    wmQosCorrelationId: string,
    wmSvcName: string,
    accept: string,
    body: UpdateWalmartFundedIncentivesEnrollmentForSpecificItemsRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SuccessfulOperation8>> {
    const req = this.createRequest('POST', '/feeds');
    const mapped = req.prepareArgs({
      feedType: [feedType, string()],
      wmSecAccessToken: [wmSecAccessToken, string()],
      wmConsumerChannelType: [wmConsumerChannelType, string()],
      wmQosCorrelationId: [wmQosCorrelationId, string()],
      wmSvcName: [wmSvcName, string()],
      accept: [accept, string()],
      body: [
        body,
        updateWalmartFundedIncentivesEnrollmentForSpecificItemsRequestSchema,
      ],
    });
    req.header('WM_SEC.ACCESS_TOKEN', mapped.wmSecAccessToken);
    req.header('WM_CONSUMER.CHANNEL.TYPE', mapped.wmConsumerChannelType);
    req.header('WM_QOS.CORRELATION_ID', mapped.wmQosCorrelationId);
    req.header('WM_SVC.NAME', mapped.wmSvcName);
    req.header('Content-Type', 'application/json');
    req.header('Accept', mapped.accept);
    req.query('feedType', mapped.feedType);
    req.json(mapped.body);
    req.authenticate(false);
    return req.callAsJson(successfulOperation8Schema, requestOptions);
  }
}
