/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  GetPricingInsightsRequest,
  getPricingInsightsRequestSchema,
} from '../models/getPricingInsightsRequest.js';
import {
  SuccessfulOperation6,
  successfulOperation6Schema,
} from '../models/successfulOperation6.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class GetPricingInsightsApi extends BaseApi {
  /**
   * Retrieve pricing insights with filters, sorting, and pagination.Use this API to get comprehensive
   * pricing insights for your items on Walmart Marketplace. You can query your catalog for various
   * pricing attributes, including current price, Buy Box pricing information, competitive pricing
   * information, repricer details, and more.
   *
   * @param wmSecAccessToken         Access token obtained from the Token API.
   *                                                                     This is required for authenticating requests
   *                                                                     to Walmart Marketplace APIs.
   * @param wmConsumerChannelType    A unique ID to identify the consumer request
   *                                                                     by channel. Use the Consumer Channel Type
   *                                                                     received during onboarding.
   * @param wmQosCorrelationId       A unique ID that identifies each API call and
   *                                                                     is used to track and debug issues. Use a
   *                                                                     randomly generated GUID for this ID.
   * @param wmSvcName                Specifies the name of the Walmart service
   *                                                                     being called.
   * @param accept
   * @param body
   * @return Response from the API call
   */
  async getPricingInsights(
    wmSecAccessToken: string,
    wmConsumerChannelType: string,
    wmQosCorrelationId: string,
    wmSvcName: string,
    accept: string,
    body: GetPricingInsightsRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SuccessfulOperation6>> {
    const req = this.createRequest('POST', '/price/getPricingInsights');
    const mapped = req.prepareArgs({
      wmSecAccessToken: [wmSecAccessToken, string()],
      wmConsumerChannelType: [wmConsumerChannelType, string()],
      wmQosCorrelationId: [wmQosCorrelationId, string()],
      wmSvcName: [wmSvcName, string()],
      accept: [accept, string()],
      body: [body, getPricingInsightsRequestSchema],
    });
    req.header('WM_SEC.ACCESS_TOKEN', mapped.wmSecAccessToken);
    req.header('WM_CONSUMER.CHANNEL.TYPE', mapped.wmConsumerChannelType);
    req.header('WM_QOS.CORRELATION_ID', mapped.wmQosCorrelationId);
    req.header('WM_SVC.NAME', mapped.wmSvcName);
    req.header('Content-Type', 'application/json');
    req.header('Accept', mapped.accept);
    req.json(mapped.body);
    req.authenticate(false);
    return req.callAsJson(successfulOperation6Schema, requestOptions);
  }
}
