/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  SuccessfulOperation5,
  successfulOperation5Schema,
} from '../models/successfulOperation5.js';
import { number, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class IncentivesApi extends BaseApi {
  /**
   * Retrieves a comprehensive list of all price incentives available for items in your catalog.
   *
   * The response includes detailed information such as Item ID, Product Name, Product URL, SKU ID,
   * Target Price, current Price, Incentive Type, Incentive Status, Base referral fee, Reduced Referral
   * Fee, Enrollment Type, Inventory count, Enrollment Date (epoch Timestamp), Expiration date (epoch
   * timestamp), Start date (epoch timestamp), and Incentive ID.
   *
   * For Walmart-funded items, the Target Price, Expiration Date, Start Date, Incentive ID, Reduced
   * Referral Fee, and Enrollment Type will not be displayed (null values). Additionally, Enrollment Type
   * and Date will not be shown for items eligible for Reduced Referral Fee incentives.
   *
   * For more information and usage examples, refer to the <a href="https://developer.walmart.com/us-
   * marketplace/docs/retrieve-price-incentives-data">Pricing API Guide</a>.
   *
   * @param limit                    Specifies the number of items to return. Allowed range is 1 to 200.
   *                                           Default is 25.
   * @param offset                   Specifies the offset of item list to be returned. Minimum offset value
   *                                           is 0.
   * @param sortBy                   Specifies the sort criteria for items.
   * @param sortOrder                Specifies the sort order for given sort criteria.
   * @param incentiveType            Specifies the incentive type to filter the incentive items.
   * @param incentiveStatus          Specifies the incentive status to retrieve items with `ELIGIBLE` or
   *                                           `ENROLLED` incentives.
   * @param wmSecAccessToken         Access token obtained from the Token API. This is required for
   *                                           authenticating requests to Walmart Marketplace APIs.
   * @param wmConsumerChannelType    A unique ID to track the consumer request by channel. Use the Consumer
   *                                           Channel Type received during onboarding.
   * @param wmQosCorrelationId       A unique ID that identifies each API call and is used to track and
   *                                           debug issues. Use a randomly generated GUID for this ID.
   * @param wmSvcName                Specifies the name of the Walmart service being called.
   * @param accept
   * @return Response from the API call
   */
  async retrievePriceIncentivesData(
    limit: number,
    offset: number,
    sortBy: string,
    sortOrder: string,
    incentiveType: string,
    incentiveStatus: string,
    wmSecAccessToken: string,
    wmConsumerChannelType: string,
    wmQosCorrelationId: string,
    wmSvcName: string,
    accept: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SuccessfulOperation5>> {
    const req = this.createRequest('GET', '/price/incentives');
    const mapped = req.prepareArgs({
      limit: [limit, number()],
      offset: [offset, number()],
      sortBy: [sortBy, string()],
      sortOrder: [sortOrder, string()],
      incentiveType: [incentiveType, string()],
      incentiveStatus: [incentiveStatus, string()],
      wmSecAccessToken: [wmSecAccessToken, string()],
      wmConsumerChannelType: [wmConsumerChannelType, string()],
      wmQosCorrelationId: [wmQosCorrelationId, string()],
      wmSvcName: [wmSvcName, string()],
      accept: [accept, string()],
    });
    req.header('WM_SEC.ACCESS_TOKEN', mapped.wmSecAccessToken);
    req.header('WM_CONSUMER.CHANNEL.TYPE', mapped.wmConsumerChannelType);
    req.header('WM_QOS.CORRELATION_ID', mapped.wmQosCorrelationId);
    req.header('WM_SVC.NAME', mapped.wmSvcName);
    req.header('Accept', mapped.accept);
    req.query('limit', mapped.limit);
    req.query('offset', mapped.offset);
    req.query('sortBy', mapped.sortBy);
    req.query('sortOrder', mapped.sortOrder);
    req.query('incentiveType', mapped.incentiveType);
    req.query('incentiveStatus', mapped.incentiveStatus);
    req.authenticate(false);
    return req.callAsJson(successfulOperation5Schema, requestOptions);
  }
}
