/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { BaseApi } from './baseApi.js';

export class MiscApi extends BaseApi {
  /**
   * @return Response from the API call
   */
  async newRequest(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/');
    req.authenticate([{ basic: true }]);
    return req.call(requestOptions);
  }
}
