/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  SuccessfulOperation,
  successfulOperationSchema,
} from '../models/successfulOperation.js';
import {
  SuccessfulOperation1,
  successfulOperation1Schema,
} from '../models/successfulOperation1.js';
import {
  UpdateRepricerStrategyRequest,
  updateRepricerStrategyRequestSchema,
} from '../models/updateRepricerStrategyRequest.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class MStrategyCollectionIdApi extends BaseApi {
  /**
   * Updates an existing repricer strategy. Use this API to modify and update a repricer strategy rule,
   * name, amount, and unit for a given strategy.
   *
   * For more information and usage examples, refer to the <a href="https://developer.walmart.com/us-
   * marketplace/docs/update-repricer-strategy">Pricing API Guide</a>.
   *
   * @param strategyCollectionId     The unique ID of the repricer strategy.
   *                                                                         This strategy collection ID is used to
   *                                                                         identify the specific repricer strategy
   *                                                                         that should be updated.
   * @param wmSecAccessToken         Access token obtained from the Token API.
   *                                                                         This is required for authenticating
   *                                                                         requests to Walmart Marketplace APIs.
   * @param wmConsumerChannelType    A unique ID to track the consumer request
   *                                                                         by channel. Use the Consumer Channel Type
   *                                                                         received during onboarding.
   * @param wmQosCorrelationId       A unique ID that identifies each API call
   *                                                                         and is used to track and debug issues. Use
   *                                                                         a randomly generated GUID for this ID.
   * @param wmSvcName                Specifies the name of the Walmart service
   *                                                                         being called.
   * @param accept
   * @param body
   * @return Response from the API call
   */
  async updateRepricerStrategy(
    strategyCollectionId: string,
    wmSecAccessToken: string,
    wmConsumerChannelType: string,
    wmQosCorrelationId: string,
    wmSvcName: string,
    accept: string,
    body: UpdateRepricerStrategyRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SuccessfulOperation>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      strategyCollectionId: [strategyCollectionId, string()],
      wmSecAccessToken: [wmSecAccessToken, string()],
      wmConsumerChannelType: [wmConsumerChannelType, string()],
      wmQosCorrelationId: [wmQosCorrelationId, string()],
      wmSvcName: [wmSvcName, string()],
      accept: [accept, string()],
      body: [body, updateRepricerStrategyRequestSchema],
    });
    req.header('WM_SEC.ACCESS_TOKEN', mapped.wmSecAccessToken);
    req.header('WM_CONSUMER.CHANNEL.TYPE', mapped.wmConsumerChannelType);
    req.header('WM_QOS.CORRELATION_ID', mapped.wmQosCorrelationId);
    req.header('WM_SVC.NAME', mapped.wmSvcName);
    req.header('Content-Type', 'application/json');
    req.header('Accept', mapped.accept);
    req.json(mapped.body);
    req.appendTemplatePath`/repricer/strategy/${mapped.strategyCollectionId}`;
    req.authenticate(false);
    return req.callAsJson(successfulOperationSchema, requestOptions);
  }

  /**
   * Deletes a repricer strategy. Use this API to delete an existing repricer strategy and its
   * corresponding details from the system.
   *
   * For more information and usage examples, refer to the <a href="https://developer.walmart.com/us-
   * marketplace/docs/delete-repricer-strategy">Pricing API Guide</a>.
   *
   * @param strategyCollectionId     The unique ID of the repricer strategy. This strategy collection ID is
   *                                           used to identify the specific repricer strategy that should be deleted.
   * @param wmSecAccessToken         Access token obtained from the Token API. This is required for
   *                                           authenticating requests to Walmart Marketplace APIs.
   * @param wmConsumerChannelType    A unique ID to track the consumer request by channel. Use the Consumer
   *                                           Channel Type received during onboarding.
   * @param wmQosCorrelationId       A unique ID that identifies each API call and is used to track and
   *                                           debug issues. Use a randomly generated GUID for this ID.
   * @param wmSvcName                Specifies the name of the Walmart service being called.
   * @param accept
   * @return Response from the API call
   */
  async deleteRepricerStrategy(
    strategyCollectionId: string,
    wmSecAccessToken: string,
    wmConsumerChannelType: string,
    wmQosCorrelationId: string,
    wmSvcName: string,
    accept: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SuccessfulOperation1>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      strategyCollectionId: [strategyCollectionId, string()],
      wmSecAccessToken: [wmSecAccessToken, string()],
      wmConsumerChannelType: [wmConsumerChannelType, string()],
      wmQosCorrelationId: [wmQosCorrelationId, string()],
      wmSvcName: [wmSvcName, string()],
      accept: [accept, string()],
    });
    req.header('WM_SEC.ACCESS_TOKEN', mapped.wmSecAccessToken);
    req.header('WM_CONSUMER.CHANNEL.TYPE', mapped.wmConsumerChannelType);
    req.header('WM_QOS.CORRELATION_ID', mapped.wmQosCorrelationId);
    req.header('WM_SVC.NAME', mapped.wmSvcName);
    req.header('Accept', mapped.accept);
    req.appendTemplatePath`/repricer/strategy/${mapped.strategyCollectionId}`;
    req.authenticate(false);
    return req.callAsJson(successfulOperation1Schema, requestOptions);
  }
}
