/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  SuccessfulOperation7,
  successfulOperation7Schema,
} from '../models/successfulOperation7.js';
import {
  UpdatePricingForASingleItemRequest,
  updatePricingForASingleItemRequestSchema,
} from '../models/updatePricingForASingleItemRequest.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class PriceApi extends BaseApi {
  /**
   * Updates the price of an item listed on Walmart Marketplace. Use this API to change the price of a
   * single item. If you want to update pricing for multiple items, we recommend using the <a href="https:
   * //developer.walmart.com/us-marketplace/reference/priceandpromotionbulkuploads">Update pricing for
   * multiple items in bulk</a> API.
   *
   * For more information and usage examples, refer to the <a href="https://developer.walmart.com/us-
   * marketplace/docs/update-pricing-for-a-single-item">Pricing API Guide</a>.
   *
   * @param wmSecAccessToken         Access token obtained from the Token
   *                                                                              API. This is required for
   *                                                                              authenticating requests to Walmart
   *                                                                              Marketplace APIs.
   * @param wmConsumerChannelType    A unique ID to track the consumer
   *                                                                              request by channel. Use the Consumer
   *                                                                              Channel Type received during
   *                                                                              onboarding.
   * @param wmQosCorrelationId       A unique ID that identifies each API
   *                                                                              call and is used to track and debug
   *                                                                              issues. Use a randomly generated GUID
   *                                                                              for this ID
   * @param wmSvcName                Specifies the name of the Walmart
   *                                                                              service being called.
   * @param accept
   * @param body
   * @return Response from the API call
   */
  async updatePricingForASingleItem(
    wmSecAccessToken: string,
    wmConsumerChannelType: string,
    wmQosCorrelationId: string,
    wmSvcName: string,
    accept: string,
    body: UpdatePricingForASingleItemRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SuccessfulOperation7>> {
    const req = this.createRequest('PUT', '/price');
    const mapped = req.prepareArgs({
      wmSecAccessToken: [wmSecAccessToken, string()],
      wmConsumerChannelType: [wmConsumerChannelType, string()],
      wmQosCorrelationId: [wmQosCorrelationId, string()],
      wmSvcName: [wmSvcName, string()],
      accept: [accept, string()],
      body: [body, updatePricingForASingleItemRequestSchema],
    });
    req.header('WM_SEC.ACCESS_TOKEN', mapped.wmSecAccessToken);
    req.header('WM_CONSUMER.CHANNEL.TYPE', mapped.wmConsumerChannelType);
    req.header('WM_QOS.CORRELATION_ID', mapped.wmQosCorrelationId);
    req.header('WM_SVC.NAME', mapped.wmSvcName);
    req.header('Content-Type', 'application/json');
    req.header('Accept', mapped.accept);
    req.json(mapped.body);
    req.authenticate(false);
    return req.callAsJson(successfulOperation7Schema, requestOptions);
  }
}
