/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AssignUnassignItemsToFromRepricerStrategyRequest,
  assignUnassignItemsToFromRepricerStrategyRequestSchema,
} from '../models/assignUnassignItemsToFromRepricerStrategyRequest.js';
import {
  SuccessfulOperation8,
  successfulOperation8Schema,
} from '../models/successfulOperation8.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class RepricerFeedsApi extends BaseApi {
  /**
   * Adds or removes one or more items from a repricer strategy. Use this API to assign or unassign
   * repricer strategies for items listed in Walmart Marketplace.
   *
   * In one feed you can update up to 10,000 items in bulk. To ensure optimal feed processing time, we
   * recommend sending no more than 1000 items in one feed and keeping the feed sizes below 10 MB.
   *
   * For more information and usage examples, refer to the <a href="https://developer.walmart.com/us-
   * marketplace/docs/assign-unassign-items-to-repricer">Pricing API Guide</a>.
   *
   * @param wmSecAccessToken         Access token obtained
   *                                                                                            from the Token API.
   *                                                                                            This is required for
   *                                                                                            authenticating requests
   *                                                                                            to Walmart Marketplace
   *                                                                                            APIs.
   * @param wmConsumerChannelType    A unique ID to track
   *                                                                                            the consumer request by
   *                                                                                            channel. Use the
   *                                                                                            Consumer Channel Type
   *                                                                                            received during
   *                                                                                            onboarding.
   * @param wmQosCorrelationId       A unique ID that
   *                                                                                            identifies each API
   *                                                                                            call and is used to
   *                                                                                            track and debug issues.
   *                                                                                            Use a randomly
   *                                                                                            generated GUID for this
   *                                                                                            ID.
   * @param wmSvcName                Specifies the name of
   *                                                                                            the Walmart service
   *                                                                                            being called.
   * @param accept
   * @param body
   * @return Response from the API call
   */
  async assignUnassignItemsToFromRepricerStrategy(
    wmSecAccessToken: string,
    wmConsumerChannelType: string,
    wmQosCorrelationId: string,
    wmSvcName: string,
    accept: string,
    body: AssignUnassignItemsToFromRepricerStrategyRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SuccessfulOperation8>> {
    const req = this.createRequest('POST', '/repricerFeeds');
    const mapped = req.prepareArgs({
      wmSecAccessToken: [wmSecAccessToken, string()],
      wmConsumerChannelType: [wmConsumerChannelType, string()],
      wmQosCorrelationId: [wmQosCorrelationId, string()],
      wmSvcName: [wmSvcName, string()],
      accept: [accept, string()],
      body: [body, assignUnassignItemsToFromRepricerStrategyRequestSchema],
    });
    req.header('WM_SEC.ACCESS_TOKEN', mapped.wmSecAccessToken);
    req.header('WM_CONSUMER.CHANNEL.TYPE', mapped.wmConsumerChannelType);
    req.header('WM_QOS.CORRELATION_ID', mapped.wmQosCorrelationId);
    req.header('WM_SVC.NAME', mapped.wmSvcName);
    req.header('Content-Type', 'application/json');
    req.header('Accept', mapped.accept);
    req.json(mapped.body);
    req.authenticate(false);
    return req.callAsJson(successfulOperation8Schema, requestOptions);
  }
}
