/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  SuccessfulOperation3,
  successfulOperation3Schema,
} from '../models/successfulOperation3.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class StrategiesApi extends BaseApi {
  /**
   * Retrieves the details of a specific repricer strategy that was previously created for items in
   * Walmart Marketplace.
   *
   * Use this API to view the list of strategies used and details about the strategy including the
   * strategy collection name, status, assigned items count, and strategy type.
   *
   * For more information and usage examples, refer to the <a href="https://developer.walmart.com/us-
   * marketplace/docs/get-repricer-strategy">Pricing API Guide</a>.
   *
   * @param wmSecAccessToken         Access token obtained from the Token API. This is required for
   *                                           authenticating requests to Walmart Marketplace APIs.
   * @param wmConsumerChannelType    A unique ID to track the consumer request by channel. Use the Consumer
   *                                           Channel Type received during onboarding.
   * @param wmQosCorrelationId       A unique ID that identifies each API call and is used to track and
   *                                           debug issues. Use a randomly generated GUID for this ID.
   * @param wmSvcName                Specifies the name of the Walmart service being called.
   * @param accept
   * @return Response from the API call
   */
  async retrieveRepricerStrategyDetails(
    wmSecAccessToken: string,
    wmConsumerChannelType: string,
    wmQosCorrelationId: string,
    wmSvcName: string,
    accept: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SuccessfulOperation3>> {
    const req = this.createRequest('GET', '/repricer/strategies');
    const mapped = req.prepareArgs({
      wmSecAccessToken: [wmSecAccessToken, string()],
      wmConsumerChannelType: [wmConsumerChannelType, string()],
      wmQosCorrelationId: [wmQosCorrelationId, string()],
      wmSvcName: [wmSvcName, string()],
      accept: [accept, string()],
    });
    req.header('WM_SEC.ACCESS_TOKEN', mapped.wmSecAccessToken);
    req.header('WM_CONSUMER.CHANNEL.TYPE', mapped.wmConsumerChannelType);
    req.header('WM_QOS.CORRELATION_ID', mapped.wmQosCorrelationId);
    req.header('WM_SVC.NAME', mapped.wmSvcName);
    req.header('Accept', mapped.accept);
    req.authenticate(false);
    return req.callAsJson(successfulOperation3Schema, requestOptions);
  }
}
