/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CreateRepricerStrategyRequest,
  createRepricerStrategyRequestSchema,
} from '../models/createRepricerStrategyRequest.js';
import {
  SuccessfulOperation,
  successfulOperationSchema,
} from '../models/successfulOperation.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class StrategyApi extends BaseApi {
  /**
   * Creates a new repricing strategy on Walmart Marketplace. A repricer strategy defines how item prices
   * should be automatically adjusted based on competitor pricing, buy box position, or other rules.
   *
   * Use this API when onboarding new pricing logic or launching a dynamic pricing strategy that responds
   * to market conditions automatically.
   *
   * For more information and usage examples, refer to the <a href="https://developer.walmart.com/us-
   * marketplace/docs/create-new-repricer-strategy">Pricing API Guide</a>.
   *
   * @param wmSecAccessToken         Access token obtained from the Token API.
   *                                                                         This is required for authenticating
   *                                                                         requests to Walmart Marketplace APIs.
   * @param wmConsumerChannelType    A unique ID to track the consumer request
   *                                                                         by channel. Use the Consumer Channel Type
   *                                                                         received during onboarding.
   * @param wmQosCorrelationId       A unique ID that identifies each API call
   *                                                                         and is used to track and debug issues. Use
   *                                                                         a randomly generated GUID for this ID.
   * @param wmSvcName                Specifies the name of the Walmart service
   *                                                                         being called.
   * @param accept
   * @param body
   * @return Response from the API call
   */
  async createRepricerStrategy(
    wmSecAccessToken: string,
    wmConsumerChannelType: string,
    wmQosCorrelationId: string,
    wmSvcName: string,
    accept: string,
    body: CreateRepricerStrategyRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SuccessfulOperation>> {
    const req = this.createRequest('POST', '/repricer/strategy');
    const mapped = req.prepareArgs({
      wmSecAccessToken: [wmSecAccessToken, string()],
      wmConsumerChannelType: [wmConsumerChannelType, string()],
      wmQosCorrelationId: [wmQosCorrelationId, string()],
      wmSvcName: [wmSvcName, string()],
      accept: [accept, string()],
      body: [body, createRepricerStrategyRequestSchema],
    });
    req.header('WM_SEC.ACCESS_TOKEN', mapped.wmSecAccessToken);
    req.header('WM_CONSUMER.CHANNEL.TYPE', mapped.wmConsumerChannelType);
    req.header('WM_QOS.CORRELATION_ID', mapped.wmQosCorrelationId);
    req.header('WM_SVC.NAME', mapped.wmSvcName);
    req.header('Content-Type', 'application/json');
    req.header('Accept', mapped.accept);
    req.json(mapped.body);
    req.authenticate(false);
    return req.callAsJson(successfulOperationSchema, requestOptions);
  }
}
