/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  TokenApiClientCredentials,
  tokenApiClientCredentialsSchema,
} from '../models/tokenApiClientCredentials.js';
import { number, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class TokenApi extends BaseApi {
  /**
   * Obtain access tokens for API authentication using OAuth 2.0 by providing Client ID and Client Secret.
   * This endpoint supports multiple grant types for different authentication scenarios - Client
   * Credentials Grant, Authorization Code Grant, Refresh Token Grant.
   *
   * An access token expires after a certain interval, so you will have to refresh a user's access token.
   * You could use refresh token, obtained from the token API call using authorization code grant type,
   * to get a new access token. <b>Token Lifetimes</b><br /><ul><li><b>Access Token:</b> 15 minutes (900
   * seconds)</li><li><b>Refresh Token:</b> 1 year (365 days)</li></ul><br /> <a href="https://developer.
   * walmart.com/us-marketplace/docs/get-an-access-token">Get an access token using Token API</a>
   *
   * <a href="https://developer.walmart.com/us-marketplace/docs/get-started-as-a-seller">Get started as a
   * seller</a>
   *
   * <a href="https://developer.walmart.com/us-marketplace/docs/get-started-as-a-solution-provider">Get
   * started as a solution provider</a>
   *
   * <a href="https://developer.walmart.com/us-marketplace/docs/oauth-20-authorization">OAuth2.0
   * authorization</a>
   *
   * @param wmPartnerId              Partner ID registered in Walmart marketplace to identify a seller
   *                                           account. <br /> This field is required when `grant_type` is
   *                                           `authorization_code` or `refresh_token`.
   * @param wmConsumerChannelType    A unique ID to track the consumer request by channel. Use the Consumer
   *                                           Channel Type received during onboarding.
   * @param wmQosCorrelationId       A unique ID that identifies each API call and is used to track and
   *                                           debug issues. Use a randomly generated GUID for this ID.
   * @param wmSvcName                Specifies the name of the Walmart service being called.
   * @param accept
   * @param grantType                Type of OAuth2.0 grant requested. <br /> **Available grant types:**
   *                                           `authorization_code`, `refresh_token` and `client_credentials`
   * @param code                     Authorization code returned to your redirect URI, obtained by your
   *                                           client app when the seller authorizes your app to access the seller
   *                                           resource. <br /> This field is required when **grant_type:
   *                                           authorization_code**.
   * @param redirectUri              Redirect URI must exactly match one of the URIs registered for your
   *                                           client app, which was provided while registering the app. <br /> This
   *                                           field is required when **grant_type: authorization_code**.
   * @param refreshToken             Refresh token received as response of Authentication API with
   *                                           authorization_code grant type. Use it to exchange for a new access token
   *                                           when the current one expires. <br /> This field is required when
   *                                           **grant_type: refresh_token**.
   * @return Response from the API call
   */
  async tokenApi(
    wmPartnerId: number,
    wmConsumerChannelType: string,
    wmQosCorrelationId: string,
    wmSvcName: string,
    accept: string,
    grantType: string,
    code: string,
    redirectUri: string,
    refreshToken: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TokenApiClientCredentials>> {
    const req = this.createRequest('POST', '/token');
    const mapped = req.prepareArgs({
      wmPartnerId: [wmPartnerId, number()],
      wmConsumerChannelType: [wmConsumerChannelType, string()],
      wmQosCorrelationId: [wmQosCorrelationId, string()],
      wmSvcName: [wmSvcName, string()],
      accept: [accept, string()],
      grantType: [grantType, string()],
      code: [code, string()],
      redirectUri: [redirectUri, string()],
      refreshToken: [refreshToken, string()],
    });
    req.header('WM_PARTNER.ID', mapped.wmPartnerId);
    req.header('WM_CONSUMER.CHANNEL.TYPE', mapped.wmConsumerChannelType);
    req.header('WM_QOS.CORRELATION_ID', mapped.wmQosCorrelationId);
    req.header('WM_SVC.NAME', mapped.wmSvcName);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.header('Accept', mapped.accept);
    req.form({
      grant_type: mapped.grantType,
      code: mapped.code,
      redirect_uri: mapped.redirectUri,
      refresh_token: mapped.refreshToken,
    });
    req.authenticate([{ basic: true }]);
    return req.callAsJson(tokenApiClientCredentialsSchema, requestOptions);
  }
}
