/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  SuccessfulOperation4,
  successfulOperation4Schema,
} from '../models/successfulOperation4.js';
import { boolean, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class WfpreferenceApi extends BaseApi {
  /**
   * Updates the enrollment status of all items in the Walmart-funded incentives program. By default, all
   * items are auto-enrolled in Walmart-funded incentives, meaning that eligible items are automatically
   * included in these programs to benefit from price reductions funded by Walmart.
   *
   * If you wish to permanently turn off Walmart-funded incentives for all items in your catalog, you can
   * use this API to set the Walmart-funded incentives program status to `OFF`. The default value of this
   * variable is `ON`. Any changes to preferences will lock in (disable) the preference option for a
   * period of 4 hours, as indicated by the `isDisabled` response field of the API.
   *
   * For more information and usage examples, refer to the <a href="https://developer.walmart.com/us-
   * marketplace/docs/manage-enrollment-all-items-in-walmart-funded-incentives">Pricing API Guide</a>
   *
   * @param autoEnrollEnabled        Specify the boolean for enabling auto enrollment. Examples of the
   *                                            allowed values are `true` or `false`.
   * @param wmSecAccessToken         Access token obtained from the Token API. This is required for
   *                                            authenticating requests to Walmart Marketplace APIs.
   * @param wmConsumerChannelType    A unique ID to identify the consumer request by channel. Use the
   *                                            Consumer Channel Type received during onboarding.
   * @param wmQosCorrelationId       A unique ID that identifies each API call and is used to track and
   *                                            debug issues. Use a randomly generated GUID for this ID.
   * @param wmSvcName                Specifies the name of the Walmart service being called.
   * @param accept
   * @return Response from the API call
   */
  async updateWalmartFundedIncentivesEnrollmentForAllItems(
    autoEnrollEnabled: boolean,
    wmSecAccessToken: string,
    wmConsumerChannelType: string,
    wmQosCorrelationId: string,
    wmSvcName: string,
    accept: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SuccessfulOperation4>> {
    const req = this.createRequest('PUT', '/price/incentives/wfpreference');
    const mapped = req.prepareArgs({
      autoEnrollEnabled: [autoEnrollEnabled, boolean()],
      wmSecAccessToken: [wmSecAccessToken, string()],
      wmConsumerChannelType: [wmConsumerChannelType, string()],
      wmQosCorrelationId: [wmQosCorrelationId, string()],
      wmSvcName: [wmSvcName, string()],
      accept: [accept, string()],
    });
    req.header('WM_SEC.ACCESS_TOKEN', mapped.wmSecAccessToken);
    req.header('WM_CONSUMER.CHANNEL.TYPE', mapped.wmConsumerChannelType);
    req.header('WM_QOS.CORRELATION_ID', mapped.wmQosCorrelationId);
    req.header('WM_SVC.NAME', mapped.wmSvcName);
    req.header('Accept', mapped.accept);
    req.query('autoEnrollEnabled', mapped.autoEnrollEnabled);
    req.authenticate(false);
    return req.callAsJson(successfulOperation4Schema, requestOptions);
  }
}
