/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Item1, item1Schema } from './item1.js';
import { ItemFeedHeader, itemFeedHeaderSchema } from './itemFeedHeader.js';

export interface AssignUnassignItemsToFromRepricerStrategyRequest {
  itemFeedHeader: ItemFeedHeader;
  item: Item1[];
  additionalProperties?: Record<string, unknown>;
}

export const assignUnassignItemsToFromRepricerStrategyRequestSchema: Schema<AssignUnassignItemsToFromRepricerStrategyRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        itemFeedHeader: ['ItemFeedHeader', itemFeedHeaderSchema],
        item: ['Item', array(item1Schema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
