/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Value, valueSchema } from './value.js';

export interface ClientCredentialsRes {
  summary: string;
  value: Value;
  additionalProperties?: Record<string, unknown>;
}

export const clientCredentialsResSchema: Schema<ClientCredentialsRes> = lazy(
  () =>
    typedExpandoObject(
      { summary: ['summary', string()], value: ['value', valueSchema] },
      'additionalProperties',
      optional(unknown())
    )
);
