/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CurrentPrice {
  currency: string;
  amount: number;
  additionalProperties?: Record<string, unknown>;
}

export const currentPriceSchema: Schema<CurrentPrice> = typedExpandoObject(
  { currency: ['currency', string()], amount: ['amount', number()] },
  'additionalProperties',
  optional(unknown())
);
