/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Filter {
  name: string;
  operator: string;
  value: number[];
  additionalProperties?: Record<string, unknown>;
}

export const filterSchema: Schema<Filter> = typedExpandoObject(
  {
    name: ['name', string()],
    operator: ['operator', string()],
    value: ['value', array(number())],
  },
  'additionalProperties',
  optional(unknown())
);
