/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Filter, filterSchema } from './filter.js';
import { SearchCriteria, searchCriteriaSchema } from './searchCriteria.js';
import { Sort, sortSchema } from './sort.js';

export interface GetPricingInsightsRequest {
  filter: Filter[];
  searchCriteria: SearchCriteria;
  sort: Sort;
  pageNumber: number;
  additionalProperties?: Record<string, unknown>;
}

export const getPricingInsightsRequestSchema: Schema<GetPricingInsightsRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        filter: ['filter', array(filterSchema)],
        searchCriteria: ['searchCriteria', searchCriteriaSchema],
        sort: ['sort', sortSchema],
        pageNumber: ['pageNumber', number()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
