/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface IncentivesEnrollment {
  referralFeeIncentiveEnrollment: string;
  incentiveType: string;
  incentiveId: string;
  additionalProperties?: Record<string, unknown>;
}

export const incentivesEnrollmentSchema: Schema<IncentivesEnrollment> = typedExpandoObject(
  {
    referralFeeIncentiveEnrollment: [
      'referralFeeIncentiveEnrollment',
      string(),
    ],
    incentiveType: ['incentiveType', string()],
    incentiveId: ['incentiveId', string()],
  },
  'additionalProperties',
  optional(unknown())
);
