/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Strategy5, strategy5Schema } from './strategy5.js';

export interface Item1 {
  strategy: Strategy5;
  additionalProperties?: Record<string, unknown>;
}

export const item1Schema: Schema<Item1> = lazy(() =>
  typedExpandoObject(
    { strategy: ['Strategy', strategy5Schema] },
    'additionalProperties',
    optional(unknown())
  )
);
