/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Item {
  itemId: string;
  productName: string;
  productUrl: string;
  productImageUrl: string;
  skuId: string;
  currentPrice: number;
  targetPrice: number;
  shippingPrice: number;
  incentiveType: string;
  baseReferralFee: number;
  reducedReferralFee: number;
  enrollmentType: string;
  enrollmentDate: string;
  incentiveStatus: string;
  inventoryCount: number;
  startDate: string;
  expirationDate: string;
  incentiveId: string;
  additionalProperties?: Record<string, unknown>;
}

export const itemSchema: Schema<Item> = typedExpandoObject(
  {
    itemId: ['itemId', string()],
    productName: ['productName', string()],
    productUrl: ['productUrl', string()],
    productImageUrl: ['productImageUrl', string()],
    skuId: ['skuId', string()],
    currentPrice: ['currentPrice', number()],
    targetPrice: ['targetPrice', number()],
    shippingPrice: ['shippingPrice', number()],
    incentiveType: ['incentiveType', string()],
    baseReferralFee: ['baseReferralFee', number()],
    reducedReferralFee: ['reducedReferralFee', number()],
    enrollmentType: ['enrollmentType', string()],
    enrollmentDate: ['enrollmentDate', string()],
    incentiveStatus: ['incentiveStatus', string()],
    inventoryCount: ['inventoryCount', number()],
    startDate: ['startDate', string()],
    expirationDate: ['expirationDate', string()],
    incentiveId: ['incentiveId', string()],
  },
  'additionalProperties',
  optional(unknown())
);
