/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ItemFeedHeader {
  processMode: string;
  subset: string;
  mart: string;
  sellingChannel: string;
  version: string;
  locale: string;
  additionalProperties?: Record<string, unknown>;
}

export const itemFeedHeaderSchema: Schema<ItemFeedHeader> = typedExpandoObject(
  {
    processMode: ['processMode', string()],
    subset: ['subset', string()],
    mart: ['mart', string()],
    sellingChannel: ['sellingChannel', string()],
    version: ['version', string()],
    locale: ['locale', string()],
  },
  'additionalProperties',
  optional(unknown())
);
