/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ItemIdentifiers {
  sku: string;
  additionalProperties?: Record<string, unknown>;
}

export const itemIdentifiersSchema: Schema<ItemIdentifiers> = typedExpandoObject(
  { sku: ['sku', string()] },
  'additionalProperties',
  optional(unknown())
);
