/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ItemPriceResponse {
  mart: string;
  message: string;
  sku: string;
  additionalProperties?: Record<string, unknown>;
}

export const itemPriceResponseSchema: Schema<ItemPriceResponse> = typedExpandoObject(
  {
    mart: ['mart', string()],
    message: ['message', string()],
    sku: ['sku', string()],
  },
  'additionalProperties',
  optional(unknown())
);
