/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface MpItemFeedHeader {
  businessUnit: string;
  version: string;
  locale: string;
  additionalProperties?: Record<string, unknown>;
}

export const mpItemFeedHeaderSchema: Schema<MpItemFeedHeader> = typedExpandoObject(
  {
    businessUnit: ['businessUnit', string()],
    version: ['version', string()],
    locale: ['locale', string()],
  },
  'additionalProperties',
  optional(unknown())
);
