/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PromoDiscount, promoDiscountSchema } from './promoDiscount.js';

export interface MpItem {
  promoDiscount: PromoDiscount;
  additionalProperties?: Record<string, unknown>;
}

export const mpItemSchema: Schema<MpItem> = lazy(() =>
  typedExpandoObject(
    { promoDiscount: ['Promo&Discount', promoDiscountSchema] },
    'additionalProperties',
    optional(unknown())
  )
);
