/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PageContext {
  pageNo: number;
  currentPageCount: number;
  totalCount: number;
  totalPages: number;
  additionalProperties?: Record<string, unknown>;
}

export const pageContextSchema: Schema<PageContext> = typedExpandoObject(
  {
    pageNo: ['pageNo', number()],
    currentPageCount: ['currentPageCount', number()],
    totalCount: ['totalCount', number()],
    totalPages: ['totalPages', number()],
  },
  'additionalProperties',
  optional(unknown())
);
