/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { CurrentPrice, currentPriceSchema } from './currentPrice.js';

export interface Pricing {
  currentPriceType: string;
  currentPrice: CurrentPrice;
  additionalProperties?: Record<string, unknown>;
}

export const pricingSchema: Schema<Pricing> = lazy(() =>
  typedExpandoObject(
    {
      currentPriceType: ['currentPriceType', string()],
      currentPrice: ['currentPrice', currentPriceSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
