/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PricingInsightsResponseList {
  itemName: string;
  sku: string;
  currentPrice: number;
  buyBoxBasePrice: number;
  buyBoxTotalPrice: number;
  buyBoxWinRate: string;
  competitorPrice: number;
  comparisonPrice: number;
  fulfillment: string;
  inventoryCount: string | null;
  repricerStrategyType: string | null;
  repricerStrategyName: string | null;
  repricerStatus: string | null;
  repricerMinPrice: string | null;
  repricerMaxPrice: string | null;
  priceCompetitiveScore: number;
  promoStatus: string | null;
  potentialGmvLift: string | null;
  gmv30: number;
  inDemand: boolean;
  priceDifferential: string | null;
  traffic: string | null;
  priceCompetitive: boolean;
  reducedReferralStatus: string | null;
  walmartFundedStatus: string;
  additionalProperties?: Record<string, unknown>;
}

export const pricingInsightsResponseListSchema: Schema<PricingInsightsResponseList> = typedExpandoObject(
  {
    itemName: ['itemName', string()],
    sku: ['sku', string()],
    currentPrice: ['currentPrice', number()],
    buyBoxBasePrice: ['buyBoxBasePrice', number()],
    buyBoxTotalPrice: ['buyBoxTotalPrice', number()],
    buyBoxWinRate: ['buyBoxWinRate', string()],
    competitorPrice: ['competitorPrice', number()],
    comparisonPrice: ['comparisonPrice', number()],
    fulfillment: ['fulfillment', string()],
    inventoryCount: ['inventoryCount', nullable(string())],
    repricerStrategyType: ['repricerStrategyType', nullable(string())],
    repricerStrategyName: ['repricerStrategyName', nullable(string())],
    repricerStatus: ['repricerStatus', nullable(string())],
    repricerMinPrice: ['repricerMinPrice', nullable(string())],
    repricerMaxPrice: ['repricerMaxPrice', nullable(string())],
    priceCompetitiveScore: ['priceCompetitiveScore', number()],
    promoStatus: ['promoStatus', nullable(string())],
    potentialGmvLift: ['potentialGmvLift', nullable(string())],
    gmv30: ['gmv30', number()],
    inDemand: ['inDemand', boolean()],
    priceDifferential: ['priceDifferential', nullable(string())],
    traffic: ['traffic', nullable(string())],
    priceCompetitive: ['priceCompetitive', boolean()],
    reducedReferralStatus: ['reducedReferralStatus', nullable(string())],
    walmartFundedStatus: ['walmartFundedStatus', string()],
  },
  'additionalProperties',
  optional(unknown())
);
