/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  WalmartFundedIncentivesEnrollment,
  walmartFundedIncentivesEnrollmentSchema,
} from './walmartFundedIncentivesEnrollment.js';

export interface Programs {
  walmartFundedIncentivesEnrollment: WalmartFundedIncentivesEnrollment;
  additionalProperties?: Record<string, unknown>;
}

export const programsSchema: Schema<Programs> = lazy(() =>
  typedExpandoObject(
    {
      walmartFundedIncentivesEnrollment: [
        'WalmartFundedIncentivesEnrollment',
        walmartFundedIncentivesEnrollmentSchema,
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
