/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ItemIdentifiers, itemIdentifiersSchema } from './itemIdentifiers.js';
import { Programs, programsSchema } from './programs.js';

export interface ProgramAction {
  itemIdentifiers: ItemIdentifiers;
  programs: Programs;
  additionalProperties?: Record<string, unknown>;
}

export const programActionSchema: Schema<ProgramAction> = lazy(() =>
  typedExpandoObject(
    {
      itemIdentifiers: ['ItemIdentifiers', itemIdentifiersSchema],
      programs: ['Programs', programsSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
