/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ItemIdentifiers, itemIdentifiersSchema } from './itemIdentifiers.js';
import { Programs1, programs1Schema } from './programs1.js';

export interface ProgramAction1 {
  itemIdentifiers: ItemIdentifiers;
  programs: Programs1;
  additionalProperties?: Record<string, unknown>;
}

export const programAction1Schema: Schema<ProgramAction1> = lazy(() =>
  typedExpandoObject(
    {
      itemIdentifiers: ['ItemIdentifiers', itemIdentifiersSchema],
      programs: ['Programs', programs1Schema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
