/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  IncentivesEnrollment,
  incentivesEnrollmentSchema,
} from './incentivesEnrollment.js';

export interface Programs1 {
  incentivesEnrollment: IncentivesEnrollment;
  additionalProperties?: Record<string, unknown>;
}

export const programs1Schema: Schema<Programs1> = lazy(() =>
  typedExpandoObject(
    {
      incentivesEnrollment: [
        'IncentivesEnrollment',
        incentivesEnrollmentSchema,
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
