/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProgramActionFeedHeader {
  requestId: string;
  requestBatchId: string;
  processMode: string;
  subset: string;
  sellingChannel: string;
  version: string;
  locale: string;
  feedDate: string;
  feedType: string;
  additionalProperties?: Record<string, unknown>;
}

export const programActionFeedHeaderSchema: Schema<ProgramActionFeedHeader> = typedExpandoObject(
  {
    requestId: ['requestId', string()],
    requestBatchId: ['requestBatchId', string()],
    processMode: ['processMode', string()],
    subset: ['subset', string()],
    sellingChannel: ['sellingChannel', string()],
    version: ['version', string()],
    locale: ['locale', string()],
    feedDate: ['feedDate', string()],
    feedType: ['feedType', string()],
  },
  'additionalProperties',
  optional(unknown())
);
