/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PromoDiscount {
  sku: string;
  price: number;
  msrp: number;
  additionalProperties?: Record<string, unknown>;
}

export const promoDiscountSchema: Schema<PromoDiscount> = typedExpandoObject(
  {
    sku: ['sku', string()],
    price: ['price', number()],
    msrp: ['msrp', number()],
  },
  'additionalProperties',
  optional(unknown())
);
