/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Scopes {
  reports: string;
  item: string;
  price: string;
  lagtime: string;
  feeds: string;
  returns: string;
  orders: string;
  inventory: string;
  content: string;
  additionalProperties?: Record<string, unknown>;
}

export const scopesSchema: Schema<Scopes> = typedExpandoObject(
  {
    reports: ['reports', string()],
    item: ['item', string()],
    price: ['price', string()],
    lagtime: ['lagtime', string()],
    feeds: ['feeds', string()],
    returns: ['returns', string()],
    orders: ['orders', string()],
    inventory: ['inventory', string()],
    content: ['content', string()],
  },
  'additionalProperties',
  optional(unknown())
);
