/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SearchCriteria {
  searchField: string;
  searchValue: string[];
  additionalProperties?: Record<string, unknown>;
}

export const searchCriteriaSchema: Schema<SearchCriteria> = typedExpandoObject(
  {
    searchField: ['searchField', string()],
    searchValue: ['searchValue', array(string())],
  },
  'additionalProperties',
  optional(unknown())
);
