/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Sort {
  sortField: string;
  sortOrder: string;
  additionalProperties?: Record<string, unknown>;
}

export const sortSchema: Schema<Sort> = typedExpandoObject(
  { sortField: ['sortField', string()], sortOrder: ['sortOrder', string()] },
  'additionalProperties',
  optional(unknown())
);
