/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface StatusInfo {
  subsidyEnrolled: boolean;
  subsidyPreference: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const statusInfoSchema: Schema<StatusInfo> = typedExpandoObject(
  {
    subsidyEnrolled: ['subsidyEnrolled', boolean()],
    subsidyPreference: ['subsidyPreference', boolean()],
  },
  'additionalProperties',
  optional(unknown())
);
