/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Strategy5 {
  sku: string;
  repricerStrategy: string;
  minimumSellerAllowedPrice: number;
  maximumSellerAllowedPrice: number;
  additionalProperties?: Record<string, unknown>;
}

export const strategy5Schema: Schema<Strategy5> = typedExpandoObject(
  {
    sku: ['sku', string()],
    repricerStrategy: ['repricerStrategy', string()],
    minimumSellerAllowedPrice: ['minimumSellerAllowedPrice', number()],
    maximumSellerAllowedPrice: ['maximumSellerAllowedPrice', number()],
  },
  'additionalProperties',
  optional(unknown())
);
