/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Strategy {
  strategyType: string;
  adjustmentType: string;
  adjustmentValue: number;
  additionalProperties?: Record<string, unknown>;
}

export const strategySchema: Schema<Strategy> = typedExpandoObject(
  {
    strategyType: ['strategyType', string()],
    adjustmentType: ['adjustmentType', string()],
    adjustmentValue: ['adjustmentValue', number()],
  },
  'additionalProperties',
  optional(unknown())
);
