/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PageContext, pageContextSchema } from './pageContext.js';
import {
  PricingInsightsResponseList,
  pricingInsightsResponseListSchema,
} from './pricingInsightsResponseList.js';

export interface SuccessfulOperation6 {
  pageContext: PageContext;
  pricingInsightsResponseList: PricingInsightsResponseList[];
  additionalProperties?: Record<string, unknown>;
}

export const successfulOperation6Schema: Schema<SuccessfulOperation6> = lazy(
  () =>
    typedExpandoObject(
      {
        pageContext: ['pageContext', pageContextSchema],
        pricingInsightsResponseList: [
          'pricingInsightsResponseList',
          array(pricingInsightsResponseListSchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
