/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Scopes, scopesSchema } from './scopes.js';

export interface SuccessfulOperation2 {
  expireAt: string;
  issuedAt: string;
  isValid: boolean;
  scopes: Scopes;
  additionalProperties?: Record<string, unknown>;
}

export const successfulOperation2Schema: Schema<SuccessfulOperation2> = lazy(
  () =>
    typedExpandoObject(
      {
        expireAt: ['expire_at', string()],
        issuedAt: ['issued_at', string()],
        isValid: ['is_valid', boolean()],
        scopes: ['scopes', scopesSchema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
