/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  StrategyCollection,
  strategyCollectionSchema,
} from './strategyCollection.js';

export interface SuccessfulOperation3 {
  totalElements: number;
  strategyCollections: StrategyCollection[];
  additionalProperties?: Record<string, unknown>;
}

export const successfulOperation3Schema: Schema<SuccessfulOperation3> = lazy(
  () =>
    typedExpandoObject(
      {
        totalElements: ['totalElements', number()],
        strategyCollections: [
          'strategyCollections',
          array(strategyCollectionSchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
