/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Item, itemSchema } from './item.js';
import { PageContext, pageContextSchema } from './pageContext.js';

export interface SuccessfulOperation5 {
  pageContext: PageContext;
  items: Item[];
  additionalProperties?: Record<string, unknown>;
}

export const successfulOperation5Schema: Schema<SuccessfulOperation5> = lazy(
  () =>
    typedExpandoObject(
      {
        pageContext: ['pageContext', pageContextSchema],
        items: ['items', array(itemSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
