/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SuccessfulOperation1 {
  message: string;
  additionalProperties?: Record<string, unknown>;
}

export const successfulOperation1Schema: Schema<SuccessfulOperation1> = typedExpandoObject(
  { message: ['message', string()] },
  'additionalProperties',
  optional(unknown())
);
