/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SuccessfulOperation11 {
  feedId: string;
  message: string;
  additionalProperties?: Record<string, unknown>;
}

export const successfulOperation11Schema: Schema<SuccessfulOperation11> = typedExpandoObject(
  { feedId: ['feedId', string()], message: ['message', string()] },
  'additionalProperties',
  optional(unknown())
);
