/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { StatusInfo, statusInfoSchema } from './statusInfo.js';

export interface SuccessfulOperation12 {
  martId: string;
  statusInfo: StatusInfo;
  additionalProperties?: Record<string, unknown>;
}

export const successfulOperation12Schema: Schema<SuccessfulOperation12> = lazy(
  () =>
    typedExpandoObject(
      {
        martId: ['martId', string()],
        statusInfo: ['statusInfo', statusInfoSchema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
