/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SuccessfulOperation4 {
  autoEnrollEnabled: boolean;
  isDisabled: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const successfulOperation4Schema: Schema<SuccessfulOperation4> = typedExpandoObject(
  {
    autoEnrollEnabled: ['autoEnrollEnabled', boolean()],
    isDisabled: ['isDisabled', boolean()],
  },
  'additionalProperties',
  optional(unknown())
);
