/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ItemPriceResponse,
  itemPriceResponseSchema,
} from './itemPriceResponse.js';

export interface SuccessfulOperation7 {
  itemPriceResponse: ItemPriceResponse;
  additionalProperties?: Record<string, unknown>;
}

export const successfulOperation7Schema: Schema<SuccessfulOperation7> = lazy(
  () =>
    typedExpandoObject(
      { itemPriceResponse: ['ItemPriceResponse', itemPriceResponseSchema] },
      'additionalProperties',
      optional(unknown())
    )
);
