/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ClientCredentialsRes,
  clientCredentialsResSchema,
} from './clientCredentialsRes.js';
import { RefreshTokenRes, refreshTokenResSchema } from './refreshTokenRes.js';
import { TokenApiRes, tokenApiResSchema } from './tokenApiRes.js';

export interface TokenApiRefreshToken {
  clientCredentialsRes: ClientCredentialsRes;
  tokenApiRes: TokenApiRes;
  refreshTokenRes: RefreshTokenRes;
  accessToken: string;
  tokenType: string;
  expiresIn: number;
  additionalProperties?: Record<string, unknown>;
}

export const tokenApiRefreshTokenSchema: Schema<TokenApiRefreshToken> = lazy(
  () =>
    typedExpandoObject(
      {
        clientCredentialsRes: [
          'clientCredentialsRes',
          clientCredentialsResSchema,
        ],
        tokenApiRes: ['tokenAPIRes', tokenApiResSchema],
        refreshTokenRes: ['refreshTokenRes', refreshTokenResSchema],
        accessToken: ['access_token', string()],
        tokenType: ['token_type', string()],
        expiresIn: ['expires_in', number()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
