/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Value1, value1Schema } from './value1.js';

export interface TokenApiRes {
  summary: string;
  value: Value1;
  additionalProperties?: Record<string, unknown>;
}

export const tokenApiResSchema: Schema<TokenApiRes> = lazy(() =>
  typedExpandoObject(
    { summary: ['summary', string()], value: ['value', value1Schema] },
    'additionalProperties',
    optional(unknown())
  )
);
