/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ProgramAction, programActionSchema } from './programAction.js';
import {
  ProgramActionFeedHeader,
  programActionFeedHeaderSchema,
} from './programActionFeedHeader.js';

export interface UpdateWalmartFundedIncentivesEnrollmentForSpecificItemsRequest {
  programActionFeedHeader: ProgramActionFeedHeader;
  programAction: ProgramAction[];
  additionalProperties?: Record<string, unknown>;
}

export const updateWalmartFundedIncentivesEnrollmentForSpecificItemsRequestSchema: Schema<UpdateWalmartFundedIncentivesEnrollmentForSpecificItemsRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        programActionFeedHeader: [
          'ProgramActionFeedHeader',
          programActionFeedHeaderSchema,
        ],
        programAction: ['ProgramAction', array(programActionSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
