/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Strategy, strategySchema } from './strategy.js';

export interface UpdateRepricerStrategyRequest {
  repricerStrategy: string;
  enabled: boolean;
  enableRepricerForPromotion: boolean;
  restoreSellerPriceWithoutTarget: boolean;
  enableBuyboxMeetExternal: boolean;
  compareWith3POfferOnly: boolean;
  strategies: Strategy[];
  additionalProperties?: Record<string, unknown>;
}

export const updateRepricerStrategyRequestSchema: Schema<UpdateRepricerStrategyRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        repricerStrategy: ['repricerStrategy', string()],
        enabled: ['enabled', boolean()],
        enableRepricerForPromotion: ['enableRepricerForPromotion', boolean()],
        restoreSellerPriceWithoutTarget: [
          'restoreSellerPriceWithoutTarget',
          boolean(),
        ],
        enableBuyboxMeetExternal: ['enableBuyboxMeetExternal', boolean()],
        compareWith3POfferOnly: ['compareWith3pOfferOnly', boolean()],
        strategies: ['strategies', array(strategySchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
