/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ProgramAction1, programAction1Schema } from './programAction1.js';
import {
  ProgramActionFeedHeader,
  programActionFeedHeaderSchema,
} from './programActionFeedHeader.js';

export interface UpdateReducedReferralFeeIncentivesEnrollmentRequest {
  programActionFeedHeader: ProgramActionFeedHeader;
  programAction: ProgramAction1[];
  additionalProperties?: Record<string, unknown>;
}

export const updateReducedReferralFeeIncentivesEnrollmentRequestSchema: Schema<UpdateReducedReferralFeeIncentivesEnrollmentRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        programActionFeedHeader: [
          'ProgramActionFeedHeader',
          programActionFeedHeaderSchema,
        ],
        programAction: ['ProgramAction', array(programAction1Schema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
