/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { MpItem, mpItemSchema } from './mpItem.js';
import {
  MpItemFeedHeader,
  mpItemFeedHeaderSchema,
} from './mpItemFeedHeader.js';

export interface UpdatePricingForMultipleItemsInBulkNewRequest {
  mpItemFeedHeader: MpItemFeedHeader;
  mpItem: MpItem[];
  additionalProperties?: Record<string, unknown>;
}

export const updatePricingForMultipleItemsInBulkNewRequestSchema: Schema<UpdatePricingForMultipleItemsInBulkNewRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        mpItemFeedHeader: ['MPItemFeedHeader', mpItemFeedHeaderSchema],
        mpItem: ['MPItem', array(mpItemSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
