/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Pricing, pricingSchema } from './pricing.js';

export interface UpdatePricingForASingleItemRequest {
  sku: string;
  pricing: Pricing[];
  additionalProperties?: Record<string, unknown>;
}

export const updatePricingForASingleItemRequestSchema: Schema<UpdatePricingForASingleItemRequest> = lazy(
  () =>
    typedExpandoObject(
      { sku: ['sku', string()], pricing: ['pricing', array(pricingSchema)] },
      'additionalProperties',
      optional(unknown())
    )
);
