/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Value1 {
  accessToken: string;
  refreshToken: string;
  tokenType: string;
  expiresIn: number;
  additionalProperties?: Record<string, unknown>;
}

export const value1Schema: Schema<Value1> = typedExpandoObject(
  {
    accessToken: ['access_token', string()],
    refreshToken: ['refresh_token', string()],
    tokenType: ['token_type', string()],
    expiresIn: ['expires_in', number()],
  },
  'additionalProperties',
  optional(unknown())
);
