/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface WalmartFundedIncentivesEnrollment {
  walmartFundedIncentivesEnrollment: string;
  additionalProperties?: Record<string, unknown>;
}

export const walmartFundedIncentivesEnrollmentSchema: Schema<WalmartFundedIncentivesEnrollment> = typedExpandoObject(
  {
    walmartFundedIncentivesEnrollment: [
      'walmartFundedIncentivesEnrollment',
      string(),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
