/**
 * Walmart APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Xml1 {
  feedId: string;
  additionalProperties?: Record<string, unknown>;
}

export const xml1Schema: Schema<Xml1> = typedExpandoObject(
  { feedId: ['feedId', string()] },
  'additionalProperties',
  optional(unknown())
);
